const TOGGLE_IMAGE_PANEL_VISIBILITY = 'TOGGLE_IMAGE_PANEL_VISIBILITY'

const TOGGLE_IMAGE_IMPORT_PANEL_VISIBILITY = 'TOGGLE_IMAGE_IMPORT_PANEL_VISIBILITY'

const SET_IMAGE_IMPORT_METHOD = 'SET_IMAGE_IMPORT_METHOD'
const SET_IMAGE_SEARCH_SOURCE = 'SET_IMAGE_SEARCH_SOURCE'
const ADD_IMAGE_SEARCH_RESULT = 'ADD_IMAGE_SEARCH_RESULT'

const TOGGLE_IMAGE_EDITOR_VISIBILITY = 'TOGGLE_IMAGE_EDITOR_VISIBILITY'
const SELECT_IMAGE_EDITOR_TOOL = 'SELECT_IMAGE_EDITOR_TOOL'
const IMPORT_IMAGE_TO_EDITOR = 'IMPORT_IMAGE_TO_EDITOR'

const ADD_RAW_IMAGE = 'ADD_RAW_IMAGE'
const ADD_CUTOUT_IMAGE = 'ADD_CUTOUT_IMAGE'
const REMOVE_IMAGE = 'REMOVE_IMAGE'

const TOGGLE_COLLAGE_BOARD_ACTIVE = 'TOGGLE_COLLAGE_BOARD_ACTIVE'
const TOGGLE_COLLAGE_BOARD_MENU_VISIBILITY = 'TOGGLE_COLLAGE_BOARD_MENU_VISIBILITY'
const SET_COLLAGE_BACKGROUND = 'SET_COLLAGE_BACKGROUND'

const ADD_COLLAGE_ELEMENT = 'ADD_COLLAGE_ELEMENT'
const REMOVE_COLLAGE_ELEMENT = 'REMOVE_COLLAGE_ELEMENT'
const UPDATE_COLLAGE_ELEMENT = 'UPDATE_COLLAGE_ELEMENT'
const TOGGLE_SELECTED_ELEMENT = 'TOGGLE_SELECTED_ELEMENT'
